# Generated by Django 5.1.15 on 2026-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
