# Generated by Django 5.1.15 on 2026-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_large',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_medium',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_size',
            field=models.PositiveIntegerField(blank=True, help_text='Optimized size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
